export const FIRESTORE_APIKEY = ''
export const FIRESTORE_AUTHDOMAIN = ''
export const FIRESTORE_PROJECTID = ''
export const FIRESTORE_STORAGEBUCKET = ''
export const FIRESTORE_MESSAGINGSENDERID = ''
export const FIRESTORE_APPID = ''
